name: Release npm package
on:
  schedule:
    - cron: '0 20 * * 1'
  workflow_dispatch:

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  # use-check-action:
  #   uses: JDFED/drip-form/.github/workflows/check.yml@dev
  #   with:
  #     branch: dev
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: master

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.0
        with:
          node-version: '14'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: 'Install and build'
        run: |
          yarn

      - name: 'set username and useEmail'
        run: |
          git config user.name mengshang918
          git config user.email mengshang918@gmail.com

      - name: 'set npm'
        run: |
          npm set "//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}"

      - name: 'lerna command'
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          git log
          npx lerna version --yes --conventional-commits -m "chore(release): publish @s" --force-git-tag --create-release github --no-private
          git log
          npx lerna publish from-package --yes
